//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicRepo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Album
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Album()
        {
            this.Musicas = new HashSet<Musica>();
        }
    
        public int idAlbum { get; set; }
        [StringLength(50)]
        public string Nome { get; set; }
        public Nullable<int> Artista { get; set; }
        [Range(1900, 2018)]
        public int Ano { get; set; }
        public Nullable<int> Editora { get; set; }
    
        public virtual Artista Artista1 { get; set; }
        public virtual Editora Editora1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Musica> Musicas { get; set; }
    }
}
