//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicRepo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Festival
    {
        public int idFestival { get; set; }
        public string Nome { get; set; }
        public Nullable<int> Artista { get; set; }
        public string Localidade { get; set; }
    
        public virtual Artista Artista1 { get; set; }
    }
}
