//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicRepo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Festival
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Festival()
        {
            this.ArtistasFestivals = new HashSet<ArtistasFestival>();
        }
    
        public int idFestival { get; set; }
        public string Nome { get; set; }
        public Nullable<int> Artista { get; set; }
        public string Localidade { get; set; }
    
        public virtual Artista Artista1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArtistasFestival> ArtistasFestivals { get; set; }
    }
}
